### ISSUE TITLE
Brotli used, even if not in Accept-Encoding header (v4.0.0)

### ISSUE THREAD

**Issue by Guillaume-Mayer** [koajs/compress#107]
Sending Accept-Encoding: gzip, or Accept-Encoding: identity, if the response size is more than the threshold, the response get encoded with Brotli.

I used the default settings: `app.use(compress());`

I went back to 3.1.0 which works perfectly.

**Comment by jonathanong** [comment]
https://github.com/koajs/compress/commit/895fbe8592076c912af079fb9021da955db2693f these tests pass, can you make a PR with a failing test?

**Comment by Guillaume-Mayer** [comment]
I will try to

**Comment by Guillaume-Mayer** [comment]
It seems there is some state involved

**Comment by jonathanong** [comment]
cool thanks
