### ISSUE TITLE
Q: `options.defaultEncoding` default `idenity`, typo?

### ISSUE THREAD

**Issue by leaumar** [koajs/compress#127]
The default for `options.defaultEncoding` is documented to be `idenity`. Is this a typo? The word "idenity" doesn't seem to be the name of anything I can find. If it's meant to be "identity", what does that even mean in this context?

Edit: I've come across other people referring to "no encoding" as identity encoding. I guess this jargon is like the identity function in fp.

**Comment by 3imed-jaberi** [comment]
@leaumar please check these links:
- https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Content-Encoding
- https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Accept-Encoding
