### ISSUE TITLE
stream.push() after EOF

### ISSUE THREAD

**Issue by dlebedynskyi** [koajs/compress#62]
Hi, occasionally getting following error 
```
Error: stream.push() after EOF 
```

![image](https://user-images.githubusercontent.com/1182917/28981546-2ae8efa2-7920-11e7-87cd-502028d52309.png)

sometime also seeing 

```
TypeError: Cannot read property 'write' of null
  File "zlib.js", line 469, col 32, in Zlib.callback

```
only package we use that references zlib is koa-compress with next config
configuration 
```
app.use(compress({
  flush: require('zlib').Z_SYNC_FLUSH
}))
```
using node 8.
 
Any idea on why this happens and how to fix this?

**Comment by coderhaoxin** [comment]
https://github.com/koajs/compress/issues/60
