### ISSUE TITLE
Issue in v2.1.0

### ISSUE THREAD

**Issue by anjanikumar2109** [koajs/compress#74]
We are seeing issues with koa-compress v2.1.0. The issue is that node v8 upgrade is mixed up in minor release of the module. So, there are references of async/await keywords in koa-compress@2.1.0

See below code in `index.js` of the published version.

``` javascript
return async (ctx, next) => {
    ctx.vary('Accept-Encoding')

    await next()
```

**Comment by jonathanong** [comment]
@anjanikumar2109 hi i unpublished it. are you still able to download it? downgrade to v2

**Comment by anjanikumar2109** [comment]
@jonathanong It is not downloadable now. We also verified that registry link is not working for `v2.1.0`.
I guess you can close the issue.

Thanks for the quick help on this.

**Comment by anjanikumar2109** [comment]
Closing this as @jonathanong has already fixed the version issue.
