### ISSUE TITLE
consider adding `response.originalLength` property

### ISSUE THREAD

**Issue by ianstormtaylor** [koajs/compress#86]
It would be nice if this added a `response.originalLength` property to make it easy to send trace information about the "real" response length. This would mimic the existing `request.originalUrl` that Koa maintains.

**Comment by jonathanong** [comment]
the primary issue with this is that we don't know the length of streams and finding out means we have to buffer the entire body. might be better done in a downstream middleware

**Comment by jonathanong** [comment]
actually yeah, should be done downstream
